version: "3.9"

services:
  db:
    image: postgres:15
    container_name: syncnsweat_postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: syncnsweat_backend
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URI: ${DATABASE_URI}
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      SECRET_KEY: ${SECRET_KEY}
      EXERCISE_API_KEY: ${EXERCISE_API_KEY}
      EXERCISE_API_HOST: ${EXERCISE_API_HOST}
      # Add other environment variables as needed, or load from .env
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app

volumes:
  postgres_data: