"""Add Exercise table, update WorkoutExercise tbl

Revision ID: 030a0c37ad95
Revises: 94087a2ec750
Create Date: 2025-04-27 12:45:09.048920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '030a0c37ad95'
down_revision: Union[str, None] = '94087a2ec750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('body_part', sa.String(), nullable=True),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('secondary_muscles', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('equipment', sa.String(), nullable=True),
    sa.Column('gif_url', sa.String(), nullable=True),
    sa.Column('instructions', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_id'), 'exercises', ['id'], unique=False)
    op.drop_column('workout_exercises', 'description')
    op.drop_column('workout_exercises', 'equipment')
    op.drop_column('workout_exercises', 'gif_url')
    op.drop_column('workout_exercises', 'body_part')
    op.drop_column('workout_exercises', 'target')
    op.drop_column('workout_exercises', 'name')
    op.drop_column('workout_exercises', 'secondary_muscles')
    op.drop_column('workout_exercises', 'instructions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_exercises', sa.Column('instructions', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('workout_exercises', sa.Column('secondary_muscles', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('workout_exercises', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('workout_exercises', sa.Column('target', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('workout_exercises', sa.Column('body_part', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('workout_exercises', sa.Column('gif_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('workout_exercises', sa.Column('equipment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('workout_exercises', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_exercises_id'), table_name='exercises')
    op.drop_table('exercises')
    # ### end Alembic commands ###
