"""Update workout_exercise tbl

Revision ID: 0727f5e00d0f
Revises: 590c71e8b026
Create Date: 2025-04-26 15:53:15.352591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0727f5e00d0f'
down_revision: Union[str, None] = '590c71e8b026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_exercises', sa.Column('bodyPart', sa.String(), nullable=True))
    op.add_column('workout_exercises', sa.Column('target', sa.String(), nullable=True))
    op.add_column('workout_exercises', sa.Column('secondary_muscles', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('workout_exercises', sa.Column('gifUrl', sa.String(), nullable=True))
    op.add_column('workout_exercises', sa.Column('instructions', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('workout_exercises', 'muscle_group')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_exercises', sa.Column('muscle_group', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('workout_exercises', 'instructions')
    op.drop_column('workout_exercises', 'gifUrl')
    op.drop_column('workout_exercises', 'secondary_muscles')
    op.drop_column('workout_exercises', 'target')
    op.drop_column('workout_exercises', 'bodyPart')
    # ### end Alembic commands ###
