"""update workout exercise tbl 3

Revision ID: 23da1e5fd738
Revises: 381b902a4cfc
Create Date: 2025-04-27 14:16:29.608161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23da1e5fd738'
down_revision: Union[str, None] = '381b902a4cfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout_exercises', 'workout_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workout_exercises', 'exercise_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               nullable=False)
    op.drop_index('ix_workout_exercises_id', table_name='workout_exercises')
    op.create_index('idx_workout_exercise_order', 'workout_exercises', ['workout_id', 'order'], unique=True)
    op.create_foreign_key(None, 'workout_exercises', 'exercises', ['exercise_id'], ['id'], ondelete='CASCADE')
    op.drop_column('workout_exercises', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_exercises', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'workout_exercises', type_='foreignkey')
    op.drop_index('idx_workout_exercise_order', table_name='workout_exercises')
    op.create_index('ix_workout_exercises_id', 'workout_exercises', ['id'], unique=False)
    op.alter_column('workout_exercises', 'exercise_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('workout_exercises', 'workout_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
