"""Add Exercise table, update WorkoutExercise tbl 2

Revision ID: 381b902a4cfc
Revises: 030a0c37ad95
Create Date: 2025-04-27 13:27:04.594167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '381b902a4cfc'
down_revision: Union[str, None] = '030a0c37ad95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
