"""Update workout_exercise tbl 2

Revision ID: 65547feba65b
Revises: 0727f5e00d0f
Create Date: 2025-04-26 15:54:09.299519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65547feba65b'
down_revision: Union[str, None] = '0727f5e00d0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_exercises', sa.Column('body_part', sa.String(), nullable=True))
    op.drop_column('workout_exercises', 'bodyPart')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_exercises', sa.Column('bodyPart', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('workout_exercises', 'body_part')
    # ### end Alembic commands ###
