"""Update workout_exercise tbl 3

Revision ID: 94087a2ec750
Revises: 65547feba65b
Create Date: 2025-04-26 15:55:04.340203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94087a2ec750'
down_revision: Union[str, None] = '65547feba65b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_exercises', sa.Column('gif_url', sa.String(), nullable=True))
    op.drop_column('workout_exercises', 'gifUrl')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_exercises', sa.Column('gifUrl', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('workout_exercises', 'gif_url')
    # ### end Alembic commands ###
